---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: dr1s/molecule-ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
