---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
provisioner:
  name: ansible
verifier:
  name: testinfra
